"""Deterministic, schema-oriented TIDAS documents for native Brightway data."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any
from uuid import UUID, uuid5

from .utils import multilingual, number_string

VERSION = "01.00.000"
TIMESTAMP = "2000-01-01T00:00:00Z"
NAMESPACE = UUID("2197f8e8-a5e7-4a3d-95e0-5560c46a0aa6")
OWNER_UUID = str(uuid5(NAMESPACE, "tidas-bw:owner"))
FORMAT_SOURCE_UUID = str(uuid5(NAMESPACE, "tidas-bw:format-source"))


def stable_uuid(value: str) -> str:
    return str(uuid5(NAMESPACE, value))


def global_reference(
    category: str,
    uuid: str,
    description: str,
    *,
    version: str = VERSION,
) -> dict[str, Any]:
    type_name = {
        "contacts": "contact data set",
        "sources": "source data set",
        "unitgroups": "unit group data set",
        "flowproperties": "flow property data set",
        "flows": "flow data set",
        "processes": "process data set",
        "lifecyclemodels": "life cycle model data set",
        "lciamethods": "LCIA method data set",
    }[category]
    return {
        "@type": type_name,
        "@refObjectId": uuid,
        "@version": version,
        "@uri": f"../{category}/{uuid}_{version}.json",
        "common:shortDescription": multilingual(description),
    }


def owner_reference() -> dict[str, Any]:
    return global_reference("contacts", OWNER_UUID, "tidas-bw generated data owner")


def format_reference() -> dict[str, Any]:
    return global_reference("sources", FORMAT_SOURCE_UUID, "TIDAS JSON generated by tidas-bw")


def small_compliance() -> dict[str, Any]:
    return {
        "common:referenceToComplianceSystem": format_reference(),
        "common:approvalOfOverallCompliance": "Not defined",
    }


def full_compliance() -> dict[str, Any]:
    return {
        **small_compliance(),
        "common:nomenclatureCompliance": "Not defined",
        "common:methodologicalCompliance": "Not defined",
        "common:reviewCompliance": "Not defined",
        "common:documentationCompliance": "Not defined",
        "common:qualityCompliance": "Not defined",
    }


def publication(uuid: str) -> dict[str, Any]:
    return {
        "common:dataSetVersion": VERSION,
        "common:permanentDataSetURI": f"urn:uuid:{uuid}",
        "common:referenceToOwnershipOfDataSet": owner_reference(),
        "common:copyright": "false",
        "common:licenseType": "Free of charge for all users and uses",
    }


def contact_document() -> dict[str, Any]:
    return {
        "contactDataSet": {
            "@xmlns": "http://lca.jrc.it/ILCD/Contact",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@version": "1.1",
            "@xsi:schemaLocation": (
                "http://lca.jrc.it/ILCD/Contact ../../schemas/ILCD_ContactDataSet.xsd"
            ),
            "contactInformation": {
                "dataSetInformation": {
                    "common:UUID": OWNER_UUID,
                    "common:shortName": multilingual("tidas-bw"),
                    "common:name": multilingual("tidas-bw generated data owner"),
                    "classificationInformation": {
                        "common:classification": {
                            "common:class": {
                                "@level": "0",
                                "@classId": "1",
                                "#text": "Group of organisations, project",
                            }
                        }
                    },
                }
            },
            "administrativeInformation": {
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                },
                "publicationAndOwnership": publication(OWNER_UUID),
            },
        }
    }


def source_document() -> dict[str, Any]:
    return {
        "sourceDataSet": {
            "@xmlns": "http://lca.jrc.it/ILCD/Source",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@version": "1.1",
            "@xsi:schemaLocation": (
                "http://lca.jrc.it/ILCD/Source ../../schemas/ILCD_SourceDataSet.xsd"
            ),
            "sourceInformation": {
                "dataSetInformation": {
                    "common:UUID": FORMAT_SOURCE_UUID,
                    "common:shortName": multilingual("tidas-bw format and provenance"),
                    "classificationInformation": {
                        "common:classification": {
                            "common:class": {
                                "@level": "0",
                                "@classId": "1",
                                "#text": "Data set formats",
                            }
                        }
                    },
                    "sourceCitation": "tidas-bw deterministic Brightway to TIDAS migration",
                    "publicationType": "Software or database",
                    "sourceDescriptionOrComment": multilingual(
                        "Generated from an open Brightway database by tidas-bw."
                    ),
                }
            },
            "administrativeInformation": {
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                },
                "publicationAndOwnership": publication(FORMAT_SOURCE_UUID),
            },
        }
    }


def unit_group_document(uuid: str, unit: str) -> dict[str, Any]:
    return {
        "unitGroupDataSet": {
            "@xmlns": "http://lca.jrc.it/ILCD/UnitGroup",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@version": "1.1",
            "@xsi:schemaLocation": (
                "http://lca.jrc.it/ILCD/UnitGroup ../../schemas/ILCD_UnitGroupDataSet.xsd"
            ),
            "unitGroupInformation": {
                "dataSetInformation": {
                    "common:UUID": uuid,
                    "common:name": multilingual(f"Units represented by {unit}"),
                    "classificationInformation": {
                        "common:classification": {
                            "common:class": {
                                "@level": "0",
                                "@classId": "4",
                                "#text": "Other unit groups",
                            }
                        }
                    },
                },
                "quantitativeReference": {"referenceToReferenceUnit": "0"},
            },
            "modellingAndValidation": {
                "complianceDeclarations": {"compliance": small_compliance()}
            },
            "administrativeInformation": {
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                },
                "publicationAndOwnership": publication(uuid),
            },
            "units": {
                "unit": {
                    "@dataSetInternalID": "0",
                    "name": unit,
                    "meanValue": "1",
                }
            },
        }
    }


def flow_property_document(uuid: str, unit_group_uuid: str, unit: str) -> dict[str, Any]:
    return {
        "flowPropertyDataSet": {
            "@xmlns": "http://lca.jrc.it/ILCD/FlowProperty",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@version": "1.1",
            "@xsi:schemaLocation": (
                "http://lca.jrc.it/ILCD/FlowProperty ../../schemas/ILCD_FlowPropertyDataSet.xsd"
            ),
            "flowPropertiesInformation": {
                "dataSetInformation": {
                    "common:UUID": uuid,
                    "common:name": multilingual(f"Quantity in {unit}"),
                    "classificationInformation": {
                        "common:classification": {
                            "common:class": {
                                "@level": "0",
                                "@classId": "4",
                                "#text": "Other flow properties",
                            }
                        }
                    },
                },
                "quantitativeReference": {
                    "referenceToReferenceUnitGroup": global_reference(
                        "unitgroups", unit_group_uuid, f"Reference unit {unit}"
                    )
                },
            },
            "modellingAndValidation": {
                "complianceDeclarations": {"compliance": small_compliance()}
            },
            "administrativeInformation": {
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                },
                "publicationAndOwnership": publication(uuid),
            },
        }
    }


def flow_document(
    uuid: str,
    name: str,
    unit: str,
    flow_property_uuid: str,
    *,
    elementary: bool,
    categories: Sequence[str] = (),
) -> dict[str, Any]:
    classification = (
        {
            "common:elementaryFlowCategorization": {
                "common:category": _elementary_classes(categories)
            }
        }
        if elementary
        else {
            "common:classification": [
                {
                    "@name": "tidas-bw generated classification",
                    "common:class": [
                        {
                            "@level": "0",
                            "@classId": "unclassified",
                            "#text": "Unclassified product flow generated from Brightway",
                        },
                    ],
                }
            ]
        }
    )
    return {
        "flowDataSet": {
            "@xmlns": "http://lca.jrc.it/ILCD/Flow",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:ecn": "http://eplca.jrc.ec.europa.eu/ILCD/Extensions/2018/ECNumber",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@version": "1.1",
            "@locations": "../ILCDLocations.xml",
            "@xsi:schemaLocation": "http://lca.jrc.it/ILCD/Flow ../../schemas/ILCD_FlowDataSet.xsd",
            "flowInformation": {
                "dataSetInformation": {
                    "common:UUID": uuid,
                    "name": {
                        "baseName": multilingual(name),
                        "treatmentStandardsRoutes": multilingual("unspecified"),
                        "mixAndLocationTypes": multilingual("generated migration flow"),
                    },
                    "classificationInformation": classification,
                    "common:generalComment": multilingual(
                        "Original Brightway categories: "
                        + (" / ".join(str(item) for item in categories) or "not provided")
                        if elementary
                        else "No authoritative product classification was available in Brightway; this flow remains explicitly unclassified."
                    ),
                },
                "quantitativeReference": {"referenceToReferenceFlowProperty": "0"},
            },
            "modellingAndValidation": {
                "LCIMethod": {"typeOfDataSet": "Elementary flow" if elementary else "Product flow"},
                "complianceDeclarations": {"compliance": small_compliance()},
            },
            "administrativeInformation": {
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                },
                "publicationAndOwnership": publication(uuid),
            },
            "flowProperties": {
                "flowProperty": {
                    "@dataSetInternalID": "0",
                    "referenceToFlowPropertyDataSet": global_reference(
                        "flowproperties", flow_property_uuid, f"Quantity in {unit}"
                    ),
                    "meanValue": "1",
                }
            },
        }
    }


def process_document(
    uuid: str,
    name: str,
    reference_product: str,
    location: str,
    exchanges: Sequence[Mapping[str, Any]],
    *,
    reference_exchange_id: str = "0",
    reference_year: int | str | None = None,
    valid_until: int | str | None = None,
    process_type: str = "Unit process, black box",
) -> dict[str, Any]:
    time = {
        "common:referenceYear": reference_year if reference_year is not None else 2000,
        "common:timeRepresentativenessDescription": multilingual(
            "Reference year transferred from Brightway metadata."
            if reference_year is not None
            else "Reference year was unavailable; 2000 is a schema placeholder and not a scientific assertion."
        ),
    }
    if valid_until is not None:
        time["common:dataSetValidUntil"] = valid_until
    return {
        "processDataSet": {
            "@xmlns": "http://lca.jrc.it/ILCD/Process",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@version": "1.1",
            "@locations": "../ILCDLocations.xml",
            "@xsi:schemaLocation": "http://lca.jrc.it/ILCD/Process ../../schemas/ILCD_ProcessDataSet.xsd",
            "processInformation": {
                "dataSetInformation": {
                    "common:UUID": uuid,
                    "name": {
                        "baseName": multilingual(name),
                        "treatmentStandardsRoutes": multilingual("generated from Brightway"),
                        "mixAndLocationTypes": multilingual(f"at {location}"),
                    },
                    "classificationInformation": {
                        "common:classification": [
                            {
                                "@name": "tidas-bw migration",
                                "common:class": [
                                    {
                                        "@level": "0",
                                        "@classId": "generated",
                                        "#text": "Generated migration data",
                                    }
                                ],
                            }
                        ]
                    },
                    "common:generalComment": multilingual(
                        "Generated by tidas-bw from an open Brightway database."
                    ),
                },
                "quantitativeReference": {
                    "@type": "Reference flow(s)",
                    "referenceToReferenceFlow": reference_exchange_id,
                    "functionalUnitOrOther": multilingual(f"{reference_product}"),
                },
                "time": time,
                "geography": {
                    "locationOfOperationSupplyOrProduction": {"@location": location or "GLO"}
                },
                "technology": {
                    "technologyDescriptionAndIncludedProcesses": multilingual(
                        "Technology description was not available in the Brightway node."
                    )
                },
            },
            "modellingAndValidation": {
                "LCIMethodAndAllocation": {"typeOfDataSet": process_type},
                "validation": {"review": {"@type": "Not reviewed"}},
                "complianceDeclarations": {"compliance": full_compliance()},
            },
            "administrativeInformation": {
                "common:commissionerAndGoal": {
                    "common:referenceToCommissioner": owner_reference(),
                    "common:intendedApplications": multilingual(
                        "Migration between Brightway and TIDAS"
                    ),
                },
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                    "common:referenceToPersonOrEntityEnteringTheData": owner_reference(),
                },
                "publicationAndOwnership": publication(uuid),
            },
            "exchanges": {"exchange": list(exchanges)},
        }
    }


def process_exchange(
    internal_id: int,
    flow_uuid: str,
    flow_name: str,
    amount: Any,
    direction: str,
    *,
    location: str | None = None,
) -> dict[str, Any]:
    value = number_string(amount)
    result = {
        "@dataSetInternalID": str(internal_id),
        "referenceToFlowDataSet": global_reference("flows", flow_uuid, flow_name),
        "exchangeDirection": direction,
        "meanAmount": value,
        "resultingAmount": value,
        "dataDerivationTypeStatus": "Unknown derivation",
    }
    if location:
        result["location"] = location
    return result


def lifecycle_model_document(
    uuid: str,
    name: str,
    instances: Sequence[Mapping[str, Any]],
    *,
    reference_process_id: str,
) -> dict[str, Any]:
    return {
        "lifeCycleModelDataSet": {
            "@xmlns": "http://eplca.jrc.ec.europa.eu/ILCD/LifeCycleModel/2017",
            "@xmlns:acme": "http://acme.com/custom",
            "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "@locations": "../ILCDLocations.xml",
            "@version": "1.1",
            "@xsi:schemaLocation": (
                "http://eplca.jrc.ec.europa.eu/ILCD/LifeCycleModel/2017 "
                "../../schemas/ILCD_LifeCycleModelDataSet.xsd"
            ),
            "lifeCycleModelInformation": {
                "dataSetInformation": {
                    "common:UUID": uuid,
                    "name": {
                        "baseName": multilingual(name),
                        "treatmentStandardsRoutes": multilingual("Brightway graph migration"),
                        "mixAndLocationTypes": multilingual("generated model"),
                    },
                    "classificationInformation": {
                        "common:classification": [
                            {
                                "@name": "tidas-bw migration",
                                "common:class": [
                                    {
                                        "@level": "0",
                                        "@classId": "generated",
                                        "#text": "Generated migration data",
                                    }
                                ],
                            }
                        ]
                    },
                },
                "quantitativeReference": {"referenceToReferenceProcess": int(reference_process_id)},
                "technology": {"processes": {"processInstance": list(instances)}},
            },
            "modellingAndValidation": {
                "validation": {
                    "review": {"common:referenceToNameOfReviewerAndInstitution": owner_reference()}
                },
                "complianceDeclarations": {"compliance": full_compliance()},
            },
            "administrativeInformation": {
                "common:commissionerAndGoal": {
                    "common:referenceToCommissioner": owner_reference(),
                    "common:intendedApplications": multilingual(
                        "Preserve Brightway provider links in TIDAS"
                    ),
                },
                "dataEntryBy": {
                    "common:timeStamp": TIMESTAMP,
                    "common:referenceToDataSetFormat": format_reference(),
                    "common:referenceToPersonOrEntityEnteringTheData": owner_reference(),
                },
                "publicationAndOwnership": publication(uuid),
            },
        }
    }


def process_instance(
    internal_id: int,
    process_uuid: str,
    process_name: str,
    *,
    connections: Sequence[Mapping[str, Any]] = (),
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "@dataSetInternalID": str(internal_id),
        "@multiplicationFactor": "1",
        "referenceToProcess": global_reference("processes", process_uuid, process_name),
    }
    if connections:
        result["connections"] = {"outputExchange": list(connections)}
    return result


def model_connection(
    flow_uuid: str,
    downstream_ids: Sequence[int],
) -> dict[str, Any]:
    downstream = [
        {
            "@id": str(identifier),
            "@flowUUID": flow_uuid,
            "@version": VERSION,
        }
        for identifier in downstream_ids
    ]
    return {
        "@flowUUID": flow_uuid,
        "@version": VERSION,
        "downstreamProcess": downstream[0] if len(downstream) == 1 else downstream,
    }


def _elementary_classes(categories: Sequence[str]) -> list[dict[str, str]]:
    text = " / ".join(str(item).lower() for item in categories)
    if "resource" in text or "natural" in text:
        if "water" in text:
            values = (
                ("0", "2", "Resources"),
                ("1", "2.2", "Resources from water"),
            )
        elif "air" in text:
            values = (
                ("0", "2", "Resources"),
                ("1", "2.3", "Resources from air"),
            )
        elif "biosphere" in text or "biotic" in text:
            values = (
                ("0", "2", "Resources"),
                ("1", "2.4", "Resources from biosphere"),
            )
        elif "ground" in text or "soil" in text:
            values = (
                ("0", "2", "Resources"),
                ("1", "2.1", "Resources from ground"),
            )
        else:
            values = (("0", "2", "Resources"),)
    elif "water" in text:
        values = (
            ("0", "1", "Emissions"),
            ("1", "1.1", "Emissions to water"),
            ("2", "1.1.3", "Emissions to water, unspecified"),
        )
    elif "soil" in text:
        values = (
            ("0", "1", "Emissions"),
            ("1", "1.2", "Emissions to soil"),
            ("2", "1.2.3", "Emissions to soil, unspecified"),
        )
    elif "air" in text:
        values = (
            ("0", "1", "Emissions"),
            ("1", "1.3", "Emissions to air"),
            ("2", "1.3.4", "Emissions to air, unspecified"),
        )
    else:
        values = (("0", "4", "Other elementary flows"),)
    return [
        {"@level": level, "@catId": identifier, "#text": label}
        for level, identifier, label in values
    ]
